import React, { useState, useEffect } from 'react';
import { Wallet, Vote, CheckCircle2, AlertCircle, Loader2, Users, ShieldCheck } from 'lucide-react';

// ==========================================
// 🔗 SMART CONTRACT CONFIGURATION
// ==========================================
// REPLACE this with your actual deployed contract address from Hardhat
const CONTRACT_ADDRESS = "0xYourDeployedContractAddressHere"; 

// REPLACE this with your actual ABI generated by Hardhat
const CONTRACT_ABI = [
  "function getCandidates() view returns (tuple(uint256 id, string name, uint256 voteCount)[])",
  "function vote(uint256 _candidateId)",
  "function hasVoted(address _voter) view returns (bool)",
  "event VotedEvent(uint256 indexed candidateId)"
];

export default function App() {
  // --- State Management ---
  const [account, setAccount] = useState("");
  const [provider, setProvider] = useState(null);
  const [contract, setContract] = useState(null);
  const [candidates, setCandidates] = useState([]);
  const [userHasVoted, setUserHasVoted] = useState(false);
  
  // UI States
  const [isLoading, setIsLoading] = useState(false);
  const [isVoting, setIsVoting] = useState(false);
  const [errorMessage, setErrorMessage] = useState("");
  const [successMessage, setSuccessMessage] = useState("");
  const [isMockMode, setIsMockMode] = useState(false);

  // --- Initialization & Wallet Connection ---
  useEffect(() => {
    if (window.ethereum) {
      window.ethereum.request({ method: 'eth_accounts' }).then(accounts => {
        if (accounts.length > 0) {
          connectWallet();
        }
      });

      window.ethereum.on('accountsChanged', (accounts) => {
        if (accounts.length > 0) {
          setAccount(accounts[0]);
          loadContractData(accounts[0]);
        } else {
          setAccount("");
          setCandidates([]);
        }
      });
    } else {
      // Trigger Demo Mode if no MetaMask is found
      enableDemoMode();
    }
  }, []);

  const enableDemoMode = () => {
    setIsMockMode(true);
    setAccount("0x1234...5678 (Demo Mode)");
    setCandidates([
      { id: 0, name: "Alice Nakamoto", voteCount: 42 },
      { id: 1, name: "Bob Buterin", voteCount: 38 },
      { id: 2, name: "Charlie Hoskinson", voteCount: 15 }
    ]);
    setErrorMessage("MetaMask is not installed! Running in UI Demo Mode.");
  };

  const connectWallet = async () => {
    setErrorMessage("");
    if (typeof window.ethereum !== 'undefined') {
      try {
        setIsLoading(true);
        const accounts = await window.ethereum.request({ method: 'eth_requestAccounts' });
        const currentAccount = accounts[0];
        setAccount(currentAccount);
        
        // Dynamically load ethers from CDN to fix preview environment build errors
        let ethersLib = window.ethers;
        if (!ethersLib) {
          ethersLib = await new Promise((resolve, reject) => {
            const script = document.createElement('script');
            script.src = "https://cdnjs.cloudflare.com/ajax/libs/ethers/6.10.0/ethers.umd.min.js";
            script.async = true;
            script.onload = () => resolve(window.ethers);
            script.onerror = () => reject(new Error("Failed to load ethers.js"));
            document.body.appendChild(script);
          });
        }
        
        const browserProvider = new ethersLib.BrowserProvider(window.ethereum);
        const signer = await browserProvider.getSigner();
        setProvider(browserProvider);
        
        const votingContract = new ethersLib.Contract(CONTRACT_ADDRESS, CONTRACT_ABI, signer);
        setContract(votingContract);

        await loadContractData(currentAccount, votingContract);
      } catch (error) {
        console.error("Connection error:", error);
        setErrorMessage("Failed to connect wallet. Please try again.");
      } finally {
        setIsLoading(false);
      }
    } else {
      enableDemoMode();
    }
  };

  // --- Blockchain Interactions ---
  const loadContractData = async (userAddress, activeContract = contract) => {
    if (!activeContract) return;
    
    try {
      setIsLoading(true);
      const voted = await activeContract.hasVoted(userAddress);
      setUserHasVoted(voted);

      const candidatesData = await activeContract.getCandidates();
      setCandidates(candidatesData);
    } catch (error) {
      console.error("Error loading data:", error);
      if (CONTRACT_ADDRESS === "0xYourDeployedContractAddressHere") {
        setErrorMessage("Please update the CONTRACT_ADDRESS with your deployed contract.");
      }
    } finally {
      setIsLoading(false);
    }
  };

  const castVote = async (candidateId) => {
    if (isMockMode) {
      handleMockVote(candidateId);
      return;
    }

    if (!contract) return;
    setErrorMessage("");
    setSuccessMessage("");
    setIsVoting(true);

    try {
      const tx = await contract.vote(candidateId);
      await tx.wait();
      
      setSuccessMessage("Vote cast successfully! The blockchain has been updated.");
      setUserHasVoted(true);
      await loadContractData(account);
    } catch (error) {
      console.error("Voting error:", error);
      if (error.code === 'ACTION_REJECTED') {
        setErrorMessage("Transaction was rejected by user.");
      } else {
        setErrorMessage("Failed to cast vote. Make sure you haven't voted already and have enough test ETH for gas.");
      }
    } finally {
      setIsVoting(false);
    }
  };

  const handleMockVote = (id) => {
    setIsVoting(true);
    setTimeout(() => {
      setCandidates(candidates.map(c => 
        c.id === id ? { ...c, voteCount: Number(c.voteCount) + 1 } : c
      ));
      setUserHasVoted(true);
      setSuccessMessage("Vote cast successfully! (Demo Mode)");
      setIsVoting(false);
    }, 1500);
  };

  // --- Sub-components ---
  const Navbar = () => (
    <nav className="bg-slate-900 border-b border-slate-800 px-6 py-4 sticky top-0 z-50">
      <div className="max-w-6xl mx-auto flex justify-between items-center">
        <div className="flex items-center space-x-2">
          <Vote className="w-8 h-8 text-blue-500" />
          <span className="text-2xl font-bold text-white tracking-tight">Votex</span>
        </div>
        <button
          onClick={connectWallet}
          className={`flex items-center space-x-2 px-4 py-2 rounded-full font-medium transition-all ${
            account 
              ? 'bg-slate-800 text-blue-400 border border-slate-700 hover:bg-slate-700' 
              : 'bg-blue-600 text-white hover:bg-blue-700 shadow-lg shadow-blue-500/20'
          }`}
        >
          <Wallet className="w-4 h-4" />
          <span>
            {account && !isMockMode
              ? `${account.substring(0, 6)}...${account.substring(account.length - 4)}` 
              : account && isMockMode 
              ? 'Demo Wallet Connected'
              : 'Connect Wallet'}
          </span>
        </button>
      </div>
    </nav>
  );

  const StatusAlerts = () => (
    <div className="max-w-4xl mx-auto mt-6 px-6">
      {errorMessage && (
        <div className="bg-red-500/10 border border-red-500/50 text-red-400 p-4 rounded-xl flex items-start space-x-3 mb-4">
          <AlertCircle className="w-5 h-5 flex-shrink-0 mt-0.5" />
          <p>{errorMessage}</p>
        </div>
      )}
      {successMessage && (
        <div className="bg-green-500/10 border border-green-500/50 text-green-400 p-4 rounded-xl flex items-start space-x-3 mb-4">
          <CheckCircle2 className="w-5 h-5 flex-shrink-0 mt-0.5" />
          <p>{successMessage}</p>
        </div>
      )}
      {userHasVoted && !successMessage && (
        <div className="bg-blue-500/10 border border-blue-500/50 text-blue-400 p-4 rounded-xl flex items-start space-x-3 mb-4">
          <ShieldCheck className="w-5 h-5 flex-shrink-0 mt-0.5" />
          <p>Your vote has been securely recorded on the blockchain. Thank you for participating!</p>
        </div>
      )}
    </div>
  );

  return (
    <div className="min-h-screen bg-slate-950 text-slate-200 font-sans selection:bg-blue-500/30">
      <Navbar />
      
      <main className="max-w-6xl mx-auto py-12 px-6">
        <div className="text-center max-w-2xl mx-auto mb-16">
          <h1 className="text-4xl md:text-5xl font-extrabold text-white mb-6">
            Secure, Transparent, <br className="hidden md:block"/> 
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-indigo-500">
              Decentralized Voting
            </span>
          </h1>
          <p className="text-slate-400 text-lg">
            Empowering communities with trustless elections. Connect your wallet to participate in the active proposal. One wallet, one immutable vote.
          </p>
        </div>

        <StatusAlerts />

        {!account && !isLoading && (
          <div className="text-center mt-12 p-12 border border-slate-800 rounded-3xl bg-slate-900/50 backdrop-blur-sm max-w-md mx-auto">
            <Wallet className="w-16 h-16 text-slate-600 mx-auto mb-4" />
            <h2 className="text-2xl font-semibold text-white mb-2">Wallet Required</h2>
            <p className="text-slate-400 mb-6">Please connect your MetaMask wallet to view candidates and cast your vote.</p>
            <button
              onClick={connectWallet}
              className="bg-blue-600 hover:bg-blue-700 text-white px-8 py-3 rounded-xl font-medium transition-all shadow-lg shadow-blue-500/20"
            >
              Connect to Participate
            </button>
          </div>
        )}

        {isLoading && (
          <div className="flex flex-col items-center justify-center py-20">
            <Loader2 className="w-12 h-12 text-blue-500 animate-spin mb-4" />
            <p className="text-slate-400 animate-pulse">Syncing with blockchain...</p>
          </div>
        )}

        {account && !isLoading && (
          <div className="mt-12">
            <div className="flex items-center justify-between mb-8">
              <h2 className="text-2xl font-bold text-white flex items-center space-x-2">
                <Users className="w-6 h-6 text-blue-500" />
                <span>Active Candidates</span>
              </h2>
              <span className="bg-slate-800 text-slate-300 px-3 py-1 rounded-full text-sm font-medium border border-slate-700">
                Network: {isMockMode ? "Demo Mode" : "Testnet"}
              </span>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              {candidates.length > 0 ? (
                candidates.map((candidate, index) => (
                  <div 
                    key={index} 
                    className="bg-slate-900 border border-slate-800 rounded-2xl p-6 hover:border-slate-700 transition-colors group relative overflow-hidden"
                  >
                    <div className="absolute -right-10 -top-10 w-32 h-32 bg-blue-500/5 rounded-full blur-2xl group-hover:bg-blue-500/10 transition-colors"></div>
                    
                    <div className="relative z-10">
                      <div className="flex justify-between items-start mb-6">
                        <div>
                          <p className="text-sm font-medium text-slate-500 mb-1">ID: #{candidate.id.toString()}</p>
                          <h3 className="text-xl font-bold text-white">{candidate.name}</h3>
                        </div>
                        <div className="bg-slate-950 px-4 py-2 rounded-xl border border-slate-800 flex flex-col items-center">
                          <span className="text-2xl font-black text-blue-400">{candidate.voteCount.toString()}</span>
                          <span className="text-xs font-medium text-slate-500 uppercase tracking-wider">Votes</span>
                        </div>
                      </div>

                      <button
                        onClick={() => castVote(candidate.id)}
                        disabled={userHasVoted || isVoting}
                        className={`w-full py-3 rounded-xl font-semibold flex items-center justify-center space-x-2 transition-all ${
                          userHasVoted
                            ? 'bg-slate-800 text-slate-500 cursor-not-allowed'
                            : isVoting
                            ? 'bg-blue-600/50 text-white cursor-wait'
                            : 'bg-blue-600 hover:bg-blue-500 text-white shadow-lg shadow-blue-500/20 active:scale-[0.98]'
                        }`}
                      >
                        {isVoting ? (
                          <>
                            <Loader2 className="w-5 h-5 animate-spin" />
                            <span>Processing...</span>
                          </>
                        ) : userHasVoted ? (
                          <>
                            <CheckCircle2 className="w-5 h-5" />
                            <span>Vote Recorded</span>
                          </>
                        ) : (
                          <>
                            <Vote className="w-5 h-5" />
                            <span>Vote for {candidate.name.split(' ')[0]}</span>
                          </>
                        )}
                      </button>
                    </div>
                  </div>
                ))
              ) : (
                <div className="col-span-full text-center py-12 text-slate-500 bg-slate-900/50 rounded-2xl border border-slate-800 border-dashed">
                  No candidates found on the contract. Ensure your contract is deployed and populated.
                </div>
              )}
            </div>
          </div>
        )}
      </main>
      
      <footer className="border-t border-slate-800 mt-20 py-8 text-center text-slate-500">
        <p>© 2024 Votex Decentralized Voting. Powered by Ethereum Testnet.</p>
      </footer>
    </div>
  );
}